name: Docker Continuous Delivery

on:
  push:
    branches:
      - "main"      # Runs when code is pushed to 'main'
      - "dev"       # Runs when code is pushed to 'dev'
      - "feature-*" # Runs when code is pushed to any 'feature-*' branch
    tags:
      - "*"         # Runs when a Git tag is pushed (e.g., v1.2.3)
  pull_request:
    branches:
      - "main"      # Runs when a PR is created targeting 'main'
      - "dev"       # Runs when a PR is created targeting 'dev'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}